### ISSUE TITLE
Package Name with dots

### ISSUE THREAD

**Issue by yhpoh91** [AkashBabu/lib-grpc-client-pool#1]
It seems that the library only supports package names with a single word.
If my package is "com.example.myexample", then it will fail to find the package, because all it has is "com", then within it, "example" and so on.

**Comment by AkashBabu** [comment]
Hi @yhpoh91, First of all thanks for pointing out the issue and raising a concern for the same.
Taking forward this issue has been resolved in version v1.3.0
Please update the library and start using it seamlessly
