### ISSUE TITLE
Can this be used to static client?

### ISSUE THREAD

**Issue by beautycss** [AkashBabu/lib-grpc-client-pool#2]
I saw the codes in `src` folder and found this is for dynamic client.
So have plan to support static client?

Thanks!

**Comment by AkashBabu** [comment]
That can be taken up as a feature request!
Will inform once the feature is complete.

**Comment by paambaati** [comment]
FWIW, I'm developing a Node.js client for [Liftbridge](https://github.com/liftbridge-io/liftbridge) and I'd love it if I didn't have to roll my own connection pool logic. I'll be watching this project closely, hoping this feature will land.

This library looks really good; it is well written and tests are comprehensive. Great job @AkashBabu! If you're working out of a branch, let me know and I can jump in with whatever help you need.

**Comment by AkashBabu** [comment]
Sorry for late progress on this feature request.
@beautycss Can you please elaborate on static client?

**Comment by paambaati** [comment]
@AkashBabu Basically, `protoc` can generate static bindings for a given proto file. These static bindings can give you the same RPC call methods and request/response objects, but with the additional bonus of static typings - which means better code intelligence (there’s even a TypeScript generator for the generated static JS code).

https://stackoverflow.com/questions/43216248/what-is-the-difference-between-dynamically-and-statically-generated-grpc-code — this also includes an explanation from a core gRPC-Node maintainer.

**Comment by AkashBabu** [comment]
@paambaati Thank you, that helped a lot! Will start working on it and let you know once it's done.

**Comment by AkashBabu** [comment]
TL-DR; upgrade to **v1.4.0**

This feature has been added in **v1.4.0**. Please visit this [wiki](https://github.com/AkashBabu/lib-grpc-client-pool/wiki/Static-Client---Example) for sample usage.

FYI, you must pass `staticFile: true` in options arguments for this feature to work.
